"use client";

/**
 * What to ask next, shown after an answer.
 *
 * The suggestions are generated by the backend from this user's context and the
 * question they just asked, so they move with the conversation: after a
 * certification answer they point at documents, testing and labs, not back at
 * "learn about BIS".
 *
 * They are prompts, never a menu. The composer stays live and anything typed
 * there takes precedence - these exist to save typing for the common next
 * step, not to narrow what can be asked.
 *
 * Deliberately absent while the assistant is answering, and after an
 * abstention: offering "next steps" underneath "I don't have a source for
 * that" reads as though the refusal were a stage in a workflow, when it is the
 * honest end of one.
 */

import { useChat } from "./ChatProvider";

export default function FollowUpSuggestions() {
  const { suggestions, sendMessage, isLoading, messages, hasConversation } = useChat();

  const last = messages[messages.length - 1];
  const lastWasAnAnswer = last?.role === "assistant" && !last.abstained;

  if (!hasConversation || isLoading || !lastWasAnAnswer || suggestions.length === 0) {
    return null;
  }

  return (
    <div className="mt-1">
      <p className="mb-2 text-xs font-medium uppercase tracking-wide text-gray-400">
        You may also want to check
      </p>
      <div className="flex flex-wrap gap-2">
        {suggestions.slice(0, 4).map((suggestion) => (
          <button
            key={suggestion}
            type="button"
            onClick={() => void sendMessage(suggestion)}
            className="rounded-lg border border-[var(--color-border)] bg-white px-3 py-1.5 text-sm text-gray-700 transition hover:border-[var(--color-navy)] hover:text-[var(--color-navy)] focus:outline-none focus:ring-2 focus:ring-[var(--color-navy)]/30 dark:bg-white/[0.04] dark:text-gray-300"
          >
            {suggestion}
          </button>
        ))}
      </div>
    </div>
  );
}
