import T from "@/components/i18n/T";
import type { Metadata } from "next";
import Link from "next/link";
import { getStandardBySlug, MOCK_CATALOGUE, standardSlug } from "@/lib/mock-catalogue";
import AnsweredFromChatBanner from "@/components/chat/AnsweredFromChatBanner";

type Props = { params: Promise<{ slug: string }> };

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const standard = getStandardBySlug((await params).slug);
  return { title: standard ? standard.is_number : "Standard details" };
}

export default async function StandardDetailPage({ params }: Props) {
  const standard = getStandardBySlug((await params).slug);
  if (!standard) return <main className="flex-1 bg-gray-50" id="main-content"><div className="mx-auto max-w-3xl px-4 py-16 text-center"><h1 className="text-2xl font-bold text-gray-900"><T k="sd.notFound" /></h1><p className="mt-2 text-sm text-gray-600"><T k="sd.notFoundBody" /></p><Link href="/standards" className="mt-6 inline-block font-medium text-[var(--color-navy)]"><T k="sd.back" /></Link></div></main>;
  const related = MOCK_CATALOGUE.filter((item) => item.category === standard.category && item.is_number !== standard.is_number).slice(0, 3);
  return <main className="flex-1 overflow-y-auto bg-gray-50" id="main-content"><div className="mx-auto w-full max-w-5xl px-4 py-8 sm:px-6 lg:px-8"><AnsweredFromChatBanner /><Link href="/standards" className="text-sm font-medium text-[var(--color-navy)]">← <T k="sd.back" /></Link><section className="mt-5 rounded-xl border border-[var(--color-border)] bg-white shadow-sm"><div className="border-b border-gray-200 bg-[var(--color-navy-lighter)] px-5 py-6 sm:px-8"><div className="flex flex-wrap items-center gap-3"><span className="rounded border border-[var(--color-navy)]/20 bg-white px-2.5 py-1 font-mono text-sm font-semibold text-[var(--color-navy)]">{standard.is_number}</span><span className="rounded-full bg-green-100 px-2.5 py-1 text-xs font-semibold text-green-800">{standard.status}</span></div><h1 className="mt-4 max-w-3xl text-2xl font-bold text-gray-900">{standard.title}</h1><p className="mt-2 text-sm text-gray-600">{standard.category} · <T k="sd.published" /> {standard.year}</p></div><div className="grid gap-8 px-5 py-7 sm:px-8 lg:grid-cols-[1fr_280px]"><div><h2 className="text-sm font-semibold uppercase tracking-wide text-gray-500"><T k="sd.scope" /></h2><p className="mt-3 text-base leading-7 text-gray-700">{standard.scope}</p><div className="mt-7 rounded-lg border border-blue-100 bg-blue-50 p-4"><p className="text-xs font-semibold uppercase tracking-wide text-blue-800"><T k="sd.note" /></p><p className="mt-1 text-sm leading-6 text-blue-900"><T k="sd.noteBody" /></p></div></div><aside className="space-y-5"><div><p className="text-xs font-semibold uppercase tracking-wide text-gray-500"><T k="sd.committee" /></p><p className="mt-1 text-sm font-medium text-gray-900">{standard.committee}</p></div><div><p className="text-xs font-semibold uppercase tracking-wide text-gray-500"><T k="sd.relatedCert" /></p><p className="mt-1 text-sm font-medium text-gray-900">{standard.scheme}</p></div><Link href={`/chat?q=Tell me about ${standard.is_number}`} className="block rounded-lg bg-[var(--color-navy)] px-4 py-3 text-center text-sm font-semibold text-white hover:bg-[var(--color-navy-light)]"><T k="sd.ask" /></Link></aside></div></section><section className="mt-8"><h2 className="text-lg font-semibold text-gray-900"><T k="sd.related" /></h2><div className="mt-3 grid gap-3 md:grid-cols-3">{related.map((item) => <Link key={item.is_number + item.title} href={`/standards/${standardSlug(item.is_number)}`} className="rounded-lg border border-gray-200 bg-white p-4 shadow-sm hover:border-[var(--color-navy)]"><span className="font-mono text-xs font-semibold text-[var(--color-navy)]">{item.is_number}</span><h3 className="mt-2 text-sm font-semibold text-gray-900">{item.title}</h3></Link>)}</div></section></div></main>;
}